module.exports = {
  url: "https://myma.net",
  name: "myMA",
  buildDate: new Date().toISOString().slice(0, 10),
  blogPageSize: 15,
  staticPaths: [
    "/",
    "/about/",
    "/how-it-works/",
    "/features/",
    "/features-branded-agent-page/",
    "/features-plan-comparison/",
    "/features-mobile-app/",
    "/features-enrollment-dashboard/",
    "/why-myma/",
    "/pricing/",
    "/agencies/",
    "/faq/",
    "/demo/",
    "/booked-demo/",
    "/resources/",
    "/compare-call-centers/",
    "/privacy/",
    "/terms/",
    "/disclaimer/",
  ],
};
